### ISSUE TITLE
Unable to install extensions

### ISSUE THREAD

**Issue by NathanealV** [pomdtr/sunbeam#13]
I've tried installing the file browser plugin with the following commands but they both result in a manifest validation error (seen below):
`sunbeam extension browse` -> `select file-browser`
`sunbeam extension install --name file-browser https://github.com/pomdtr/sunbeam-file-browser`

Error:
```Cloning into '/tmp/sunbeam1982198270'...
[I#] [S#] doesn't validate with http://github.com/sunbeamlauncher/sunbeam/manifest#
  [I#] [S#/required] missing properties: 'scripts'
  [I#/rootItems] [S#/properties/rootItems]
    [I#/rootItems/0] [S#/properties/rootItems/items]
      [I#/rootItems/0] [S#/properties/rootItems/items/required] missing properties: 'script'
      [I#/rootItems/0] [S#/properties/rootItems/items/additionalProperties] additionalProperties 'command' not allowed
    [I#/rootItems/1] [S#/properties/rootItems/items]
      [I#/rootItems/1] [S#/properties/rootItems/items/required] missing properties: 'script'
      [I#/rootItems/1] [S#/properties/rootItems/items/additionalProperties] additionalProperties 'command' not allowed
    [I#/rootItems/2] [S#/properties/rootItems/items]
      [I#/rootItems/2] [S#/properties/rootItems/items/required] missing properties: 'script'
      [I#/rootItems/2/with/root] [S#/properties/rootItems/items/properties/with/patternProperties/%5E%5Ba-zA-Z%5D%5Ba-zA-Z0-9-_%5D+$/anyOf] anyOf failed
        [I#/rootItems/2/with/root] [S#/properties/rootItems/items/properties/with/patternProperties/%5E%5Ba-zA-Z%5D%5Ba-zA-Z0-9-_%5D+$/anyOf/0/type] expected string, but got object
        [I#/rootItems/2/with/root] [S#/properties/rootItems/items/properties/with/patternProperties/%5E%5Ba-zA-Z%5D%5Ba-zA-Z0-9-_%5D+$/anyOf/1/type] expected boolean, but got object
      [I#/rootItems/2] [S#/properties/rootItems/items/additionalProperties] additionalProperties 'command' not allowed
    [I#/rootItems/3] [S#/properties/rootItems/items]
      [I#/rootItems/3] [S#/properties/rootItems/items/required] missing properties: 'script'
      [I#/rootItems/3] [S#/properties/rootItems/items/additionalProperties] additionalProperties 'command' not allowed
  [I#] [S#/additionalProperties] additionalProperties 'commands' not allowedError: jsonschema: '' does not validate with http://github.com/sunbeamlauncher/sunbeam/manifest#/required: missing properties: 'scripts'
```

I installed sunbeam using homebrew:
`brew install pomdtr/tap/sunbeam`

Edit: This applies to all the extensions listed in the browse section.

**Comment by pomdtr** [comment]
Thanks for flagging this !

I'm still working on the manifest config, so the demo extensions are often broken.

Until the api stabilize, the best way to play with sunbeam is to:

1. install the project from the main branch `go install github.com/pomdtr/sunbeam@main`
2. run/install the extension from the example folder: `sunbeam extension install bitwarden extensions/bitwarden`

**Comment by NathanealV** [comment]
Thank you for the reply :) I've tried running those commands (modified a bit) and it says that the extension has been installed but I cannot find these extensions with `sunbeam extension list` or use them.

Commands:
- `go install github.com/pomdtr/sunbeam@main`
- Clone the `sunbeam` git repo and cd into it
- `sunbeam extension install file-browser examples/file-browser`

**Comment by pomdtr** [comment]
Yep the extension install add a typo, can you retry ?

**Comment by NathanealV** [comment]
Same issue, even with the latest install of the master branch. No errors either unfortunately

**Comment by pomdtr** [comment]
Ok I'll push a new update tomorrow which should fix it.

**Comment by NathanealV** [comment]
No worries! I'm on Windows but using WSL2 with Go installed if that helps

**Comment by pomdtr** [comment]
The extension system has been dropped for simplicity, so I'll close this one
