### ISSUE TITLE
Documentation for installing extensions is wrong

### ISSUE THREAD

**Issue by dewinterjack** [pomdtr/sunbeam#41]
![Screenshot 2023-05-29 at 10 14 00](https://github.com/pomdtr/sunbeam/assets/17269242/d9a49f32-9a68-4564-bebb-a1e05fe1a4a1)

![Screenshot 2023-05-29 at 10 14 15](https://github.com/pomdtr/sunbeam/assets/17269242/6c390b7c-69cd-4050-b557-fa841e641f6c)

**Comment by pomdtr** [comment]
Sry about that, looking at it right now

**Comment by dewinterjack** [comment]
I was on 0.9 - an upgrade to 1.0.0 fixed the issue for me, thanks! It may be helpful to have a notification to update if there are breaking changes.
