### ISSUE TITLE
Python no longer supported?

### ISSUE THREAD

**Issue by dewinterjack** [pomdtr/sunbeam#42]
I just updated to 1.0.0 from 0.9. My python script is no longer runnable:
![Screenshot 2023-05-29 at 10 57 23](https://github.com/pomdtr/sunbeam/assets/17269242/e52a1b7f-6ac1-4afc-9d81-685105bd17c6)
I notice in the docs python is not one of the languages mentioned and it is not in the extension create command.
Is this intended? I would be happy to add python support but it would be good to get a bit of context around the error I'm getting and thoughts on python support.

**Comment by pomdtr** [comment]
You just need to add execution permission + a shebang to your files:

1. add `#/usr/bin/env python3` at the first line of your file
2. give it execution permissions: chmod +x ./files.py

Sunbeam does not really care about the language your script uses, it just needs to get a get a valid json string on stdout.

**Comment by dewinterjack** [comment]
ahh it was the permissions that I hadn't done - thanks for that!

**Comment by pomdtr** [comment]
Maybe sunbeam should show you a warning in that case. I don't want to run `chmod +x` for you though

**Comment by pomdtr** [comment]
wdyt of this ?

<img width="1060" alt="image" src="https://github.com/pomdtr/sunbeam/assets/17577332/4099af51-3b42-46e1-a488-9b6773bf366a">
