### ISSUE TITLE
Most commands return a `Page validation error`

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#48]
Hi! 
As a fan of Raycast I am super keen in trying sunbeam but I can't get it to work as expected.

I tried `files` and `github` but both fail.
Here is the error for `files`

 ## Page validation error

 validation error: /items/1/actions/0

 Current page:

 ```json
 {
   "items": [
     {
       "accessories": [
         "/mypath/myfolder"
       ],
       "actions": [
         {
           "target": "/mypath/myfolder/test",
           "title": "Open File",
           "type": "open"
         },
         {
           "key": "y",
           "text": "/mypath/myfolder/test",
           "title": "Copy Path",
           "type": "copy"
         }
       ],
       "title": "test"
     },
     {
       "accessories": [
         "/mypath/myfolder"
       ],
       "actions": [
         {
           "command": [
             "/Users/xxx/Library/Application Support/sunbeam/extensions/files/src/sunbeam-extension",
             "/mypath/myfolder/testdir"
           ],
           "title": "Browse Directory",
           "type": "push"
         },
         {
           "key": "y",
           "text": "/mypath/myfolder/testdir",
           "title": "Copy Path",
           "type": "copy"
         }
       ],
       "title": "testdir"
     }
   ],
   "type": "list"
 }
 ```

It works if I don't have a folder and just files but is a bit limited then 😄

**Comment by pomdtr** [comment]
Sorry about that, the last release is probably not up to date (I introduced the `push` type quite recently).

**Comment by b-per** [comment]
No worries! I could see that `main` was fixed and was about to install it but I just saw the new release. All good now! Ready to play and start creating my own extensions!

**Comment by pomdtr** [comment]
Please report any bugs you encounter, I want to squash them before the V1 release!
