### ISSUE TITLE
Add support for Opt + left/right/delete and Cmd + left/right/delete in the search bar

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#49]
It would be great to be able to use `Opt + left/right` and `Cmd + left/right` to navigate the search string at the top. I personally have muscle memory of `Opt + del` to remove the last word and it doesn't work in sunbeam.

**Comment by pomdtr** [comment]
fixed the opt issue. Cmd is not available on the terminal, you need to use ctrl+a / ctrl+e (it works in raycast btw!)
