### ISSUE TITLE
Can't trigger `alt + ...` shortcuts on Mac OS

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#52]
Using `"key" : ...` allows to set a shortcut for a command, but on Mac OS, I have not been able to trigger them. 
There is no `alt` key, so I have tried `control`, `option` and `command` but none of them seemed to work.

**Comment by pomdtr** [comment]
You need to setup your terminal to handle option as meta: https://www.shell-tips.com/mac/meta-key/#gsc.tab=0. I'll update the readme
