### ISSUE TITLE
Quitting sunbeam with `esc` returns a non-zero exit code

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#53]
If I execute sunbeam and leave it by pressing `esc` the shell returns an exit code of `1` (e.g. error), when I would expect it to return a 0.

**Comment by pomdtr** [comment]
This is expected.

It is useful when you use sunbeam in a pipe (ex: sunbeam my-command | other-command). 

If you cancel your selection, you will be able to detect it from the shell and not run the following command.

**Comment by b-per** [comment]
OK, so there is a reason for it.
I use Warp as a terminal though and those error 1 look odd there though as they are highlighted in red.

Here is a quick example of running `sunbeam files` vs `broot/br`
![image](https://github.com/pomdtr/sunbeam/assets/8754100/25ea155b-ab7a-4b9e-aad6-6b7ba133a4bd)

**Comment by pomdtr** [comment]
I though about it, and I think a good middle ground would be to only return set the exit code to 1 if sunbeam is part of a pipe

**Comment by pomdtr** [comment]
fixed by d775b8ccb95c661429b29b6f4464e1cbe1a6b3e8
