### ISSUE TITLE
Feature Request - Use glow for the `detail` type to pretty print Markdown

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#56]
charmbracelet has [a nice tool](https://github.com/charmbracelet/glow) called glow to display markdown on the CLI

Knowing that `sunbeam` already uses a few charmbracelet libraries, I was wondering if it would be possible to leverage glow to show nicer `detail` pages.

**Comment by pomdtr** [comment]
Nice suggestion! Glow use [glamour](https://github.com/charmbracelet/glamour) for syntax highlighting, and I will probably add support for highlighting code soon.

However, in split pages (ex: lists with detail text), the [text wrapping library](https://pkg.go.dev/github.com/muesli/reflow@v0.3.0) I use break the highlighting, which looks glaring. So I removed support for it for now.

You can actually see it in action in the demo gif:

<img width="869" alt="image" src="https://github.com/pomdtr/sunbeam/assets/17577332/d74c5565-a902-40c4-89f7-783dd952f44d">

**Comment by b-per** [comment]
And I wasn't aware of the ability to add `detail` to a `list` item!

**Comment by pomdtr** [comment]
I need to do a better job documenting my work :P

**Comment by pomdtr** [comment]
This is now supported through the `language` field.

See the tldr extension for an example: https://pomdtr.github.io/sunbeam/book/examples/tldr/index.html
