### ISSUE TITLE
sunbeam broken on windows since v22

### ISSUE THREAD

**Issue by st0le** [pomdtr/sunbeam#58]
v22. Straight up crashed.

v25, doesn't not print anything to console, none of the commands work.

**Comment by st0le** [comment]
Apologies, this is weird. It seems to work on a second machine. I'm going to close it and check why its broken on my first machine.

**Comment by pomdtr** [comment]
It's probably because I'm iterating on the extension system. Sorry about the trouble

**Comment by st0le** [comment]
Yes. Just realized it prints the json instead of displaying any menu. No worries. Using v21

**Comment by pomdtr** [comment]
I'll ping you once I'm done, you might need to reinstall your extensions. V1 is coming soon, I will garanty backward compatibility from there

**Comment by st0le** [comment]
@pomdtr, asking since I've seen recent changes. are you dropping support for Windows? :(

I understand wsl is an option but would appreciate if windows was also supported. Can assist in testing if that's the issue.

**Comment by pomdtr** [comment]
Hey, I plan to add support back soon, but since I did not test it yet I have removed it for now

**Comment by pomdtr** [comment]
support for windows is back on master !
