### ISSUE TITLE
`-v` or `--version` doesn't work in the latest releases

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#69]
- `sunbeam --version` returns `Error: extension --version not found` 
- and `sunbeam -v` returns `Error: extension -v not found` 
 
but `sunbeam -h` shows that the flag is valid.

```
Flags:
  -h, --help      help for sunbeam
  -v, --version   version for sunbeam
```

**Comment by pomdtr** [comment]
it should be fixed :)
