### ISSUE TITLE
Extensions in v.rc42

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#70]
I have just tested rc42 and things are working well! 

Couple of questions on extensions:

- is it still possible to install local extensions instead of extensions from GitHub?
  - I tried `./sunbeam extension install /my/path` and got `Error: command failed: URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)`
- and when installing from GitHub, could we provide a subfolder? I have created [my own repo](https://github.com/b-per/sunbeam-bper-extensions) with some extensions but I can't seem to be able to install them either locally or through GitHub

**Comment by pomdtr** [comment]
1. It looks like sunbeam is trying to `git clone` your local path. I should add more check. In order to install an extension, you need to create a `sunbeam-extension` executable, and install the folder (ex: sunbeam extension install my-dir). I'll add support for installing files.

2. Not yet, i'll think about it. In the meantime, you can store your scripts as gists, and install them using:

`sunbeam extension install --alias my-extension https://gist.github.com/a1b4482d7214f957bc04ef789aada6c6.git`

**Comment by pomdtr** [comment]
I also plan to add support for installing scripts from a raw url (ex: pastebin).

**Comment by b-per** [comment]
Thanks for the info.
I am getting some issues with the gist option though

```
./sunbeam extension install --alias tf https://gist.github.com/b-per/abcd
Cloning into '/Users/xxxx/.local/share/sunbeam/extensions/tf/src'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
Error: fork/exec /Users/xxxx/.local/share/sunbeam/extensions/tf/src/sunbeam-extension: permission denied
```

**Comment by pomdtr** [comment]
Right, gists files are not executable by default.

I'm pushing a new version of sunbeam, which introduces an `--entrypoint` flag to fix your issue.

`sunbeam extension install <git-url> --entrypoint subdir/sunbeam-script`

**Comment by pomdtr** [comment]
Yeah v43 fixes this too :)

**Comment by b-per** [comment]
I can raise another issue for it but the permission issue is still there in v43. This time I could clone my repo by using `-e` but it failed with the same error as the gist one.

**Comment by pomdtr** [comment]
Can you try running chmod +x on your scripts ?

I'll add a step in the install process to run it for you :)

**Comment by b-per** [comment]
Yes: https://github.com/b-per/sunbeam-bper-extensions

**Comment by pomdtr** [comment]
It's working for me (but sunbeam is not able to extract the manifest

```
~/sunbeam-bper-extensions (main|✔) [1]$ sunbeam extension install https://github.com/b-per/sunbeam-bper-extensions --entrypoint=gh/sunbeam-extension
Cloning into '/Users/pomdtr/.local/share/sunbeam/extensions/bper-extensions/src'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (31/31), done.
remote: Total 35 (delta 2), reused 29 (delta 2), pack-reused 0
Receiving objects: 100% (35/35), 296.48 KiB | 4.49 MiB/s, done.
Resolving deltas: 100% (2/2), done.
Error: command failed: Error: unknown flag: --json
```

**Comment by b-per** [comment]
Oh! 
I was using `entrypoint=gh` and not `entrypoint=gh/sunbeam-extension` , it works with the file name at the end.

Yes, now I need to update the extensions to work with the new JSON schemas.

**Comment by pomdtr** [comment]
I'll add support for this too, it's a valid usecase :)

**Comment by pomdtr** [comment]
pushed a new release :)
