### ISSUE TITLE
`command` only accepts a string, not allowing multiple parameters

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#76]
Might be a user error but as part of porting an older extension I got an error saying that the `command` parameter for the action of type `run` only accepts string as input type, while it used to accept list of strings as well. 

Right now, providing a command like `sunbeam command subcommand` it fails, giving a `sunbeam command subcommand not found`

Should we allow list of strings?

**Comment by pomdtr** [comment]
Can you give me more detail on the command in question ?

Sunbeam does not work with positional args anymore, instead you are supposed to pass inputs through the `params` field.

**Comment by b-per** [comment]
Oh, I get it. This works for my use case now.

So, with this mechanism it is possible to "jump" between commands of an extension but it wouldn't be possible to trigger another extension (not sure if there would be a valid case for it)

**Comment by pomdtr** [comment]
> So, with this mechanism it is possible to "jump" between commands of an extension but it wouldn't be possible to trigger another extension (not sure if there would be a valid case for it)

Currently no. I think jumping between extensions would be too dependant on the user-defined alias. I think the share mechanism is a better way to address this (see #73)
