### ISSUE TITLE
`workDir` has been removed from the payload in `1.0.0-rc.53`

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#78]
Is it expected or a mistake? 

The `files` extension from the store doesn't work anymore for example. (And I use it in my own extensions)

**Comment by pomdtr** [comment]
Sorry about this. Maybe you can help me on that front. What do you think is the best between:

1. Having cwd set to the extension dir, and use `workDir` to find out the current directory.
2. Having cwd set to the current working directory, and using your language to find out the script dir

```
const DIRNAME=$(dirname "$0")
```

**Comment by pomdtr** [comment]
I added it back as `workdir`

**Comment by b-per** [comment]
Having the ability to know the current directory is mandatory for some commands that depend on the filesystem and read from local files.

What would be the use case to know what the directory of the extension is? Aren't all the extensions installed in the same folder with `sunbeam extension install`?

Then, personally, I don't have a preference between using `cwd` or `workdir` as long as we can get the current directory somehow.

**Comment by pomdtr** [comment]
I mean that there are two options:

- either set the current dir of the process to the user `current working dir`
- or set it as the extension dir (`.local/share/...`) and pass it via stdin (through `workdir`, `workDir`, `cwd`...)

Sunbeam used to work with the first option, but it's quite error prone when you use imports in your scripts

```sh
source ./file.sh # here we expect the relative path to be relative to the script
```

**Comment by pomdtr** [comment]
I switched to passing `cwd` via `stdin` sorry for noise

**Comment by b-per** [comment]
Yes, I think that the approach of having the "real" working directory as the script one makes sense to allow those relative imports.

**Comment by b-per** [comment]
`cwd` has been removed again, no? Is there another way to get the current directory?

**Comment by b-per** [comment]
OK. I will do more tests but I feel like when looking at it today, calling the `.` directory was actually returning the directory of the entry script and not the current working directory. 

This can be tested with the `files` command (I think the one in your repo was not working with the latest version of sunbeam but I have my own very similar version)

**Comment by pomdtr** [comment]
Oh this is a bug then, I'll fix it. Quick note, you will have to update your scripts with the latest release:

manifest:
   command mode: `page` => `list` || `detail`

command output:
   type is no longer necessary

**Comment by pomdtr** [comment]
fixed in latest release

**Comment by b-per** [comment]
With the new behaviour, is the solution to do the following?

Replacing

```bash
#!/bin/sh

# check if python3 is installed
if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is not installed"
    exit 1
fi

exec python3 "./extension.py" "$@"
```

by 

```bash
#!/bin/sh

# check if python3 is installed
if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is not installed"
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"

exec python3 "$DIR/extension.py" "$@"
```

I like splitting the most complex extensions between different files, like [here](https://github.com/b-per/sunbeam-bper-extensions/tree/main/dagster), so the previous behaviour was actually quite nice for that.

**Comment by b-per** [comment]
Also, about this

> manifest:
command mode: page => list || detail

I used to have a page conditionally being a a list (if there is data), or a detail (if there is no data), which is not possible anymore.

Is this where `emptyText` would help then?

**Comment by pomdtr** [comment]
> I like splitting the most complex extensions between different files, like [here](https://github.com/b-per/sunbeam-bper-extensions/tree/main/dagster), so the previous behaviour was actually quite nice for that.

Nice extensions btw!

It's a valid usecase. I'm a bit torn between the two options. Most of my script are composed of a single file

> Is this where emptyText would help then?

Yes it is how raycast handles it. 

Beeing able to know if the script returns a list or a detail before getting the script output allows the user to type a query even  if nothing is rendered yet.

**Comment by pomdtr** [comment]
I reverted the change on `cwd`. I agree that the `DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"` is quite arcane, and sunbeam is trying to keep it simple.

Btw, why do you use a bash script at all in this extension ?

I would just rename the `extension.py` script to `dagster.py`, and add a shebang on it:

`#!/usr/bin/env python3`

**Comment by pomdtr** [comment]
One other thing, you can set env vars in `~/.config/sunbeam/config.json` (see https://pomdtr.github.io/sunbeam/book/reference/schemas/config.html)

**Comment by b-per** [comment]
I use it because it is a boilerplate I can reuse everywhere 😆 . I could definitely change it for some extensions.

In some cases, it is not very useful, but in other ones, I use it to source env vars, adding `source ~/.sunbeamrc` to the bash script. 

With the new config file that you mentioned, I could move away from this approach.

**Comment by pomdtr** [comment]
Yeah I would just remove the `sunbeam-extension` entrypoint in most of your extensions, and just rely on the shebang. Awesome work btw, it is super cool to see my small project beeing used :)
