### ISSUE TITLE
Best way to handle external dependencies

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#79]
I am writing a few extensions and leverage quite a bit Python, the language I am more familiar with.

The issue I am trying to solve is how I could leverage `pip` packages in my Python code but still be able to distribute those extensions. This prevents using fundamentals libraries like `requests` for example.

What I found so far is that:

- if I use the `sunbeam` command from a Python venv all the pip packages of that venv are accessible
  - but in that case, all other users of the extension will need to run from a venv with the pip packages installed
- if I use the Raycast integration, those extensions don't work as we spin up a subshell that is not in the venv I use in the CLI
- my `sunbeam-extension` script could activate a venv and/or create a new one if it doesn't exist and `pip install` dependencies

For now, I have been writing extensions in "vanilla" Python and not using any pip package but it then means that I need to call `urllib.request` instead of `requests` which is not a lot of fun 😆 

Another option would be to make the extension available on HTTP but it then means that people will have to send potentially some tokens or user/pass to a black box.

What is your take on that? Should sunbeam have a mechanism to allow installing Python (and other languages) packages? It feels like a big lift though and steers away from what `sunbeam` is supposed to be.

**Comment by pomdtr** [comment]
Excellent question. As you said, handling dependency management is obviously out of scope for sunbeam.

I see two solution for this:

1. use [deno](https://deno.com/) instead of python
    - in deno, you just need to add an import statement to your scripts to declare a dependencies
2. complile an executable for your extension using [nuitka](https://github.com/Nuitka/Nuitka), then publish it as a github release
     - I plan to add support for installing extensions from github releases

**Comment by b-per** [comment]
Thanks for the inputs! It's all about trade offs.

Option 2 is clunky but at least it doesn't require me writing JS 😆 and is less black-boxy than nuitka (which people might be worried to run, not really knowing what happens).

The entrypoint script is what I was thinking as well. 

To make it easier to install such packages but still keep sunbeam unaware of those, would it be possible to provide sunbeam some `hook` script that is run before a `sunbeam extension install ...` or a `sunbeam extension upgrade ...`

**Comment by pomdtr** [comment]
Interesting idea.

Where would the hook scripts be declared ?

**Comment by pomdtr** [comment]
> Option 2 is clunky but at least it doesn't require me writing JS

You should give deno a try. 
I personally enjoy writing scripts in deno a lot more than in python.

**Comment by b-per** [comment]
I was thinking that an extension would often look like:

```
- my folder
  - sunbeam-extension
  - myfile1.py
  - myfile2.py
```

So, in that case, having a file called `install.sh` at the same level as `sunbeam-extension` would make it be called every time we install or update the extension

```
- my folder
  - sunbeam-extension
  - myfile1.py
  - myfile2.py
  - install.sh
```

**Comment by pomdtr** [comment]
My general feeling is that if you are creating an extension which requires multiple dependencies, you should probably create an executable instead.

Otherwise we might need a lot of these. Ex:

- install.sh
- upgrade.sh
- uninstall.sh
- ...

**Comment by pomdtr** [comment]
I think I have found the perfect solution for python scripts: https://github.com/jaraco/pip-run#single-script-tools-and-shebang-support

**Comment by pomdtr** [comment]
`pipx` is also an interesting solution.

https://pypa.github.io/pipx/examples/#pipx-run-examples

**Comment by b-per** [comment]
I'll have a go at it! 

It still requires installing `pip-run` on the side so it is not a complete seamless experience but might definitely help with some more complex scripts.

--- 

> Otherwise we might need a lot of these. Ex:
install.sh
upgrade.sh
uninstall.sh
...

Wouldn't it work with just 1 script, the same for install/upgrade? If dependencies are installed in the same folder as the extension I am thinking that uninstall would anyway remove those automatically

--- 

> You should give deno a try.
> I personally enjoy writing scripts in deno a lot more than in python.

The Python experienc writing sunbeam extensions is actually very nice with list/dict comprehensions (the goal of the script being generating JSON based on some inputs). 

And as soon as things get a bit complex I enjoy way too much the simplicity of `@dataclass` in Python

**Comment by pomdtr** [comment]
Feel free to contribute a pip package for sunbeam types (using TypedDict).

**Comment by pomdtr** [comment]
Here is a working script using pip-run: https://gist.github.com/pomdtr/dcbe76f237391bacba0f66e93ed6b1ac

You can run it using: 

```
sunbeam run https://gist.githubusercontent.com/pomdtr/dcbe76f237391bacba0f66e93ed6b1ac/raw/eda7f8b291fb54be5f6957932995001bab6582a7/sunbeam-python.py
```

(it will require the latest release of sunbeam)

**Comment by b-per** [comment]
I know that this one is closed (and let me know if you want me to raise a different one) but I am figuring out what is the best way to install/share my more "complex" extensions.

[This one](https://github.com/b-per/sunbeam-bper-extensions/tree/main/dagster) for example leverages some "external libraries" that I created, which means that the extension is made of multiple files.

From what I see, the current extension mechanism only allows pointing to a single github file (the previous used to allow to point to a folder and was just executing `sunbeam-extension` inside).

I could technically move all the code in one single python file but it feels like a future maintenance nightmare. If it is not possible to clone a full folder of a repo and point to a file I think that I won't be able to use extensions installed from GH for the more complex ones and would need to tell people to clone the repo and install the extension locally.

**Comment by pomdtr** [comment]
> ... would need to tell people to clone the repo and install the extension locally

I think it's a reasonable approach.

Cloning the repository is not the only issue here, as for more complex extensions sunbeam would also need to install external dependencies.

One feature that I might add later is a way to download a compiled executable from github releases. In your case, you would use something like nuitka + github actions (bundling both your project + external dependencies in a single executable).

**Comment by pomdtr** [comment]
I have written some instructions on distributing python applications (with dependencies) in https://pomdtr.github.io/sunbeam/developer-guide/publishing#example-python-apps
