### ISSUE TITLE
How to write cross OS scripts

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#81]
(sorry for another not real issue but more of a discussion)

What is the best way to write scripts which would work cross OS (e.g. on MacOS and on Windows)?

#### What doesn't work

I though of using the "launcher" bash script like it is used in some examples, and tried to write some Powershell code but Windows doesn't allow people to run Powershell on files which are not with a `ps1` file type.

#### What works

For a Python script, I added an alias for `python` where python3 is installed and added a shebang of `#!python` at the top of my Python script. Installing this extension worked on Windows (and I am pretty sure will work as well on MacOS)

Now, to read configuration set in local files, instead of using env var and `source` in the launcher script for Unix I could move this to some Python logic dependent on the OS.

#### What could be different

How could we make it more seamless for the same scripts to run on Unix and Windows (not talking about WSL)?

1. Could `sunbeam` check for `sunbeam-extension` and `sunbeam-extension.ps1` in the case of Windows? And if the `ps1` version exists, run this script instead of the one without an extension?
2. Could we define what is the entry script in text in `sunbeam-extension` (or another file) rather than using this script as an executable one?

I think I would prefer 1.  as it wouldn't require too much of a rework but I'd be keen to hear your point of view

**Comment by pomdtr** [comment]
> I though of using the "launcher" bash script like it is used in some examples, and tried to write some Powershell code but Windows doesn't allow people to run Powershell on files which are not with a ps1 file type.

What about using this as a "entry script" ?

```
#!/bin/sh

powershell my-script.ps1
```

I quite like the `sunbeam-extension.ps1` idea. I think powershell script can also be defined in a .exe file, so maybe `sunbeam-extension.exe` would be better ?

**Comment by b-per** [comment]
I just tried 
```
#!/bin/sh

powershell my-script.ps1
```
on a file without an extension and it prompted me to open an application meaning that it didn't work.

--- 

I also tried with an `exe` and got a nice
```
Program 'test.exe' failed to run: The specified executable is not a valid application for this OS platform.At line:1 char:1
```

---

But running `.\test.ps1` with the following code works well
```
python $PSScriptRoot/extension.py
```

**Comment by pomdtr** [comment]
I'll do some test on my own vm :)

**Comment by st0le** [comment]
An alternative approach to consider, bundle a sh parser. This is used in [Task](https://taskfile.dev/)

https://github.com/mvdan/sh

**Comment by pomdtr** [comment]
So currently a good strategy for writing powershell script in sunbeam is the same I use for other languages (ex: https://github.com/pomdtr/sunbeam-vscode)

1. use `sunbeam-extension` as the entrypoint:

```sh
#!/bin/sh

powershell ./extension.ps1
```

2. write your extension in powershell as usual in `extension.ps1`

I agree that it is not elegant, and one alternative I'm considering is too allow using an arbitrary extension for the entrypoint (ex: sunbeam-extension.ts, sunbeam-extension.ps1...)

Here it would allow you to do:

```
#!/usr/bin/env powershell

# your script here
```

**Comment by pomdtr** [comment]
> An alternative approach to consider, bundle a sh parser. This is used in [Task](https://taskfile.dev/)

Even if you don't use WSL, sunbeam requires a posix shell to work (on macos/linux, you already have `bin/sh`, on windows you can install it through git bash). 

I don't plan to bundle an interpreter for sunbeam: those make sense for oneliners, but the /bin/sh shell is used to run full-blown extensions.

**Comment by pomdtr** [comment]
Hey! So I though a lot about it, and I come to the conclusion that git repository is the wrong unit for sunbeam extensions.

I find sunbeam extensions are the best when they are composed of a single file, and I want to optimize the experience for this usecase (at least for v1).

I migrated all of the extensions repository to a single one (https://github.com/pomdtr/sunbeam-extensions).

As for the initial question on this issue: sunbeam runs on all platform, but extension are not required to. It is fine to use on ps1 script on windows, and one sh script on linux, or even not to have a windows version at all.

However if you want to build cross-platform scripts, sunbeam gives you tool for building cross-platfom scripts (sunbeam query / sunbeam fetch, clipboard + browser utils...). But in this case, you should not use powershell, but a cross-plaform intepreter instead (python, deno, sh...)

**Comment by pomdtr** [comment]
An alternative way to distribute python scripts is to leverage nix. See https://yukiisbo.red/notes/spice-up-with-nix-scripts/
