### ISSUE TITLE
Add `detail` to `list`

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#82]
Hi @pomdtr !

I was checking if it was still possible to add a `detail` to a `list` item, like described [here](https://github.com/pomdtr/sunbeam/issues/56#issuecomment-1637163352), but I don't see it in the JSON schemas anymore.

Was this removed in the latest refactor? And would you think of adding it back?

**Comment by pomdtr** [comment]
There is two issues with detail attached to list items:

1: highlighting issue (see https://github.com/muesli/reflow/issues/52)
2: I still need to figure out a good api for dynamic update
