### ISSUE TITLE
`rc62` - Error `stat /Users/xxx/.config/sunbeam/config.json: no such file or directory`

### ISSUE THREAD

**Issue by b-per** [pomdtr/sunbeam#83]
In `rc62`, any command returns a `stat /Users/xxx/.config/sunbeam/config.json: no such file or directory`.

To fix it, I had to:
1. create the directory `/Users/xxx/.config/sunbeam/` which didn't exist
2. do a `touch /Users/xxx/.config/sunbeam/config.json` to create an empty config file

Should the `brew install` script take care of that?

**Comment by b-per** [comment]
Actually, the `config.json` needs to be at minimum a valid JSON (like `{}`), otherwise `sunbeam` fails all the time with an invalid JSON error.

**Comment by pomdtr** [comment]
Thanks for the report, I'll fix it asap!

**Comment by pomdtr** [comment]
fixed in latest release
