### ISSUE TITLE
Distribute sunbeam as a nix flake

### ISSUE THREAD

**Issue by pomdtr** [pomdtr/sunbeam#86]

**Comment by tasmo** [comment]
What happened to this?

Using the documented command `nix shell github:pomdtr/sunbeam --command sunbeam` will not work without a `flake.nix` file.

**Comment by k0ral** [comment]
Looks like the flake [got removed](https://github.com/pomdtr/sunbeam/commit/186994fcba3f3d07c4d3bbf222c337e00d245a78) a year ago, despite [the documentation](https://sunbeam.deno.dev/docs/user-guide/installation.html) still advertising a nix-flake installation method (as of today.)
